packages:
  - "packages/*"
  - "demo/"
  - "st/"

allowBuilds:
  esbuild: false

# Define a catalog of version ranges.
catalog:
  ziko: ^2.0.0-beta.15.1
  vite: ^8.2.1
  acorn: ^8.18.0
  "@rollup/pluginutils": ^5.4.0
  unified : latest
  remark-parse : latest
  remark-rehype : latest

minimumReleaseAgeExclude:
  - ziko@2.0.0-beta.15.1
  - '@zikojs/mind-elixir@0.6.2'
